started transition to cmake

diff --git a/xbeinstd/branches/cmake-and-splitting/mqs/bootstrap b/xbeinstd/branches/cmake-and-splitting/mqs/bootstrap
--- a/xbeinstd/branches/cmake-and-splitting/mqs/bootstrap
+++ b/xbeinstd/branches/cmake-and-splitting/mqs/bootstrap
@@ -1,7 +1,10 @@
 #! /bin/sh
 # 
-# Bootstrap the project from a clean checkout (no configure available).
+# Bootstrap the project from a clean checkout.
 #
-# -i install missing files
-#ACLOCAL="aclocal -I /usr/share/autoconf-archive -I config" autoreconf -i -v -f
-autoreconf --install --force
+if test -d "build"; then
+	echo "build directory does already exist, aborting!" > /dev/stderr
+	exit 1
+else
+	mkdir build && cd build && cmake ..
+fi
